name: 'Build and Deploy app'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - feature/*
      - develop
      - master

jobs:
  autoTag:
    name: 'Auto-tag'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.taggerDryRun.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Patch version for each merge
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: ${{ github.ref != 'refs/heads/master' }} # will dry run if not master

  docker:
    name: Build Docker Images
    needs: [autoTag]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          echo -e "docker build -t containerRegistry/${{ vars.SERVICE_NAME }}:${{ needs.autoTag.outputs.version }}"

      - name: Push docker image
        run: |
          echo -e "docker push containerRegistry/${{ vars.SERVICE_NAME }}:${{ needs.autoTag.outputs.version }}"

  deploy-do:
    name: 'Deploy to DO Environment'
    runs-on: ubuntu-latest
    environment: do
    needs: docker
    steps:
      - name: Sync ArgoCD Application
        run: |
          APPLICATION_NAME="my-app-${{ vars.SERVICE_NAME }}"
          GIT_BRANCH="${{ github.ref_name }}"
          echo -e 'https://agoServer/api/v1/applications/{name}/sync'
          echo $GIT_BRANCH
          echo $APPLICATION_NAME
          # curl -X POST "https://agoServer/api/v1/applications/{name}/sync" \
          #   -H "Authorization: Bearer ${{ secrets.ARGOCD_API_KEY }}" \
          #   -H 'Content-Type: application/json' \
          #   -d "{\"name\": \"$APPLICATION_NAME\",\"revision\": \"$GIT_BRANCH\"}

